version: "3.7"

services:
  node:
    image: node
    user: "node"
    working_dir: /home/node/app
    container_name: node_dev
    volumes:
    - ./app:/home/node/app
    ports:
    - 54343:8080
    command: ["yarn", "run", "dev-server"]
